library("tidyr")
library("dplyr")

# get the base penguins data organised
penguins_nona <- penguins |>
  select(species, bill_len:body_mass) |>
  rename(bl = bill_len,
         bd = bill_dep,
         fl = flipper_len,
         bm = body_mass) |>
  na.omit()

library("ggplot2")
library("ggdist")
library("readr")
library("readxl")
library("stringr")
library("lubridate")
library("visdat")
library("janitor")
library("countrycode")
library("imputeTS")
library("forcats")
library("tidymodels")
library("colorspace")
library("RColorBrewer")
library("dichromat")
library("patchwork")
library("naniar")
library("ggbeeswarm")
library("gt")
library("MASS")
library("gganimate")
library("plotly")
library("nullabor")
library("htmltools")
library("crosstalk")
library("sugrrants")
library("brolgar")
library("tsibble")
library("feasts")
library("tsibbletalk")
library("cubble")
library("sugarbag")
library("rmapshaper")
library("cartogram")
library("sf")
library("broom")
library("broom.mixed") 
library("lme4")
library("ggthemes")
library("conflicted")
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::slice)
conflicts_prefer(dplyr::rename)
conflicts_prefer(dplyr::mutate)
conflicts_prefer(dplyr::summarise)
conflicts_prefer(viridis::viridis_pal)
conflicts_prefer(readr::col_factor)
conflicts_prefer(tsibble::pedestrian)

